service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    function:
        handler: function.php
        description: ""
        layers:
            - ${bref:layer.php-73}

# Exclude files from deployment
package:
    exclude:
        - "tests/**"
        - "infra/**"
        - ".git/**"
        - "composer.phar"
        - "exclude/**"
        - "node_modules/**"
