service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: index.php
        layers:
            - ${bref:layer.php-73-fpm}
        # This section contains the URL routing configuration of API Gateway
        events:
            - http: "ANY /"
            - http: "ANY /{proxy+}"
    function:
        handler: function.php
        description: ""
        layers:
            - ${bref:layer.php-73}

# Exclude files from deployment
package:
    exclude:
        - "tests/**"
        - "infra/**"
        - ".git/**"
        - "composer.phar"
        - "exclude/**"
        - "node_modules/**"
